apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: a18rdwfzv-nodejs 
  janus-idp.io/tekton: a18rdwfzv-nodejs
  backstage.io/kubernetes-id: a18rdwfzv-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: a18rdwfzv-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml